In [0]:
from torch.utils.data import Dataset, DataLoader
from torch import nn, from_numpy, optim
import numpy as np
#pandas- librărie pentru lucrul cu fișierele
import pandas as pd
import torch
import torch.nn as nn

In [0]:
df=pd.read_csv("/content/diabetes.csv",header=None)

In [3]:
df.values

array([[-0.294118 ,  0.487437 ,  0.180328 , ..., -0.53117  , -0.0333333,
         0.       ],
       [-0.882353 , -0.145729 ,  0.0819672, ..., -0.766866 , -0.666667 ,
         1.       ],
       [-0.0588235,  0.839196 ,  0.0491803, ..., -0.492741 , -0.633333 ,
         0.       ],
       ...,
       [-0.411765 ,  0.21608  ,  0.180328 , ..., -0.857387 , -0.7      ,
         1.       ],
       [-0.882353 ,  0.266332 , -0.0163934, ..., -0.768574 , -0.133333 ,
         0.       ],
       [-0.882353 , -0.0653266,  0.147541 , ..., -0.797609 , -0.933333 ,
         1.       ]])

In [0]:
#Dataset - o clasă din PyTorch foarte utilă gestionării seturilor de date
class DiabetesDataset(Dataset):
    """ Diabetes dataset."""
    # Initialize your data, download, etc.
    def __init__(self):
        #Citim setul de date
        df=pd.read_csv("/content/diabetes.csv",header=None, dtype=np.float32)
        xy = torch.from_numpy(df.values)
        self.len = xy.shape[0]
        #Vom folosi ca input toate valorile mai puțin ultima coloană
        self.x_data = xy[:, 0:-1]
        #Vom folosi ca output ultima coloană
        self.y_data = xy[:, [-1]]

    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]

    def __len__(self):
        return self.len

In [0]:
dataset = DiabetesDataset()
#DataLoader - un utilitar ce ne ajută să împărțim setul de date pe batch-uri și astfel să facem antrenare în mod Mini-Batch
train_loader = DataLoader(dataset=dataset,
                          batch_size=32,
                          shuffle=True,
                          num_workers=1)

In [6]:
dataset[0]

(tensor([-0.2941,  0.4874,  0.1803, -0.2929,  0.0000,  0.0015, -0.5312, -0.0333]),
 tensor([0.]))

In [0]:
class Model(nn.Module):

    def __init__(self):
        """
        In the constructor we instantiate two nn.Linear module
        """
        super(Model, self).__init__()
        self.l1 = nn.Linear(8, 6)
        self.l2 = nn.Linear(6, 4)
        self.l3 = nn.Linear(4, 1)

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        """
        In the forward function we accept a Variable of input data and we must return
        a Variable of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Variables.
        """
        out1 = self.sigmoid(self.l1(x))
        out2 = self.sigmoid(self.l2(out1))
        y_pred = self.sigmoid(self.l3(out2))
        return y_pred

In [0]:
model=Model()

In [0]:
criterion = nn.BCELoss(reduction='sum')
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [10]:
# Training loop
for epoch in range(200):
  for i, data in enumerate(train_loader, 0):
      # get the inputs
      inputs, labels = data

      # Forward pass: Compute predicted y by passing x to the model
      y_pred = model(inputs)

      # Compute and print loss
      loss = criterion(y_pred, labels)
      print(f'Epoch {epoch + 1} | Batch: {i+1} | Loss: {loss.item():.4f}')

      # Zero gradients, perform a backward pass, and update the weights.
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

Epoch 1 | Batch: 1 | Loss: 20.2431
Epoch 1 | Batch: 2 | Loss: 23.4692
Epoch 1 | Batch: 3 | Loss: 20.1881
Epoch 1 | Batch: 4 | Loss: 19.0309
Epoch 1 | Batch: 5 | Loss: 20.8728
Epoch 1 | Batch: 6 | Loss: 20.1789
Epoch 1 | Batch: 7 | Loss: 20.9373
Epoch 1 | Batch: 8 | Loss: 18.7460
Epoch 1 | Batch: 9 | Loss: 28.4625
Epoch 1 | Batch: 10 | Loss: 23.3944
Epoch 1 | Batch: 11 | Loss: 23.6523
Epoch 1 | Batch: 12 | Loss: 23.0491
Epoch 1 | Batch: 13 | Loss: 22.4534
Epoch 1 | Batch: 14 | Loss: 21.5691
Epoch 1 | Batch: 15 | Loss: 21.2487
Epoch 1 | Batch: 16 | Loss: 21.6450
Epoch 1 | Batch: 17 | Loss: 21.6213
Epoch 1 | Batch: 18 | Loss: 19.2690
Epoch 1 | Batch: 19 | Loss: 18.4667
Epoch 1 | Batch: 20 | Loss: 23.3777
Epoch 1 | Batch: 21 | Loss: 21.9526
Epoch 1 | Batch: 22 | Loss: 21.9277
Epoch 1 | Batch: 23 | Loss: 20.5190
Epoch 1 | Batch: 24 | Loss: 14.7283
Epoch 2 | Batch: 1 | Loss: 16.2554
Epoch 2 | Batch: 2 | Loss: 21.4032
Epoch 2 | Batch: 3 | Loss: 19.1647
Epoch 2 | Batch: 4 | Loss: 22.9477
Epoch

KeyboardInterrupt: ignored